# Generated by Django 5.0.6 on 2024-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('planeta_origem', models.CharField(choices=[('Terra', 'Planeta Terra'), ('Namek', 'Planeta Namek'), ('Vegeta', 'Planeta Vegeta'), ('Outros', 'Outros')], max_length=20)),
                ('raca_preferida', models.CharField(choices=[('Terráqueo', 'Terráqueo'), ('Sayajin', 'Sayajin'), ('Androide', 'Androide'), ('Outros', 'Outros')], max_length=20)),
                ('trabalho', models.CharField(choices=[('Autonomo', 'Autonomo'), ('CLT', 'CLT'), ('PJ', 'PJ'), ('Tipo Goku', 'Tipo Goku')], max_length=20)),
                ('acai_preferido', models.CharField(choices=[('Puro', 'Puro'), ('Com banana', 'Com banana'), ('Com granola', 'Com granola'), ('Com gosto de terra', 'Com gosto de terra')], max_length=20)),
                ('tamanho_preferido', models.CharField(choices=[('300ml', '300ml'), ('500ml', '500ml'), ('1000ml', '1000ml'), ('Casquinha', 'Casquinha')], max_length=20)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
